<?php

/**
 * BaseSeccionNoticia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $seccion_id
 * @property integer $importancia
 * @property integer $noticia_id
 * @property Noticia $Noticia
 * @property Seccion $Seccion
 * 
 * @method integer        getSeccionId()   Returns the current record's "seccion_id" value
 * @method integer        getImportancia() Returns the current record's "importancia" value
 * @method integer        getNoticiaId()   Returns the current record's "noticia_id" value
 * @method Noticia        getNoticia()     Returns the current record's "Noticia" value
 * @method Seccion        getSeccion()     Returns the current record's "Seccion" value
 * @method SeccionNoticia setSeccionId()   Sets the current record's "seccion_id" value
 * @method SeccionNoticia setImportancia() Sets the current record's "importancia" value
 * @method SeccionNoticia setNoticiaId()   Sets the current record's "noticia_id" value
 * @method SeccionNoticia setNoticia()     Sets the current record's "Noticia" value
 * @method SeccionNoticia setSeccion()     Sets the current record's "Seccion" value
 * 
 * @package    sf2013
 * @subpackage model
 * @author     Javi
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSeccionNoticia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('seccion_noticia');
        $this->hasColumn('seccion_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('importancia', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('noticia_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Noticia', array(
             'local' => 'noticia_id',
             'foreign' => 'id'));

        $this->hasOne('Seccion', array(
             'local' => 'seccion_id',
             'foreign' => 'id'));
    }
}