<?php

/**
 * BaseComentario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $texto
 * @property date $fecha
 * @property integer $usuario_id
 * @property integer $noticia_id
 * @property Noticia $Noticia
 * 
 * @method string     getTexto()      Returns the current record's "texto" value
 * @method date       getFecha()      Returns the current record's "fecha" value
 * @method integer    getUsuarioId()  Returns the current record's "usuario_id" value
 * @method integer    getNoticiaId()  Returns the current record's "noticia_id" value
 * @method Noticia    getNoticia()    Returns the current record's "Noticia" value
 * @method Comentario setTexto()      Sets the current record's "texto" value
 * @method Comentario setFecha()      Sets the current record's "fecha" value
 * @method Comentario setUsuarioId()  Sets the current record's "usuario_id" value
 * @method Comentario setNoticiaId()  Sets the current record's "noticia_id" value
 * @method Comentario setNoticia()    Sets the current record's "Noticia" value
 * 
 * @package    sf2013
 * @subpackage model
 * @author     Javi
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComentario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comentario');
        $this->hasColumn('texto', 'string', 140, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 140,
             ));
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('usuario_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('noticia_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Noticia', array(
             'local' => 'noticia_id',
             'foreign' => 'id'));
    }
}