<?php

/**
 * BaseAutorNoticia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $noticia_id
 * @property integer $autor_id
 * @property Noticia $Noticia
 * 
 * @method integer      getNoticiaId()  Returns the current record's "noticia_id" value
 * @method integer      getAutorId()    Returns the current record's "autor_id" value
 * @method Noticia      getNoticia()    Returns the current record's "Noticia" value
 * @method AutorNoticia setNoticiaId()  Sets the current record's "noticia_id" value
 * @method AutorNoticia setAutorId()    Sets the current record's "autor_id" value
 * @method AutorNoticia setNoticia()    Sets the current record's "Noticia" value
 * 
 * @package    sf2013
 * @subpackage model
 * @author     Javi
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAutorNoticia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('autor_noticia');
        $this->hasColumn('noticia_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('autor_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Noticia', array(
             'local' => 'noticia_id',
             'foreign' => 'id'));
    }
}