<?php

/**
 * BaseNoticia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $titulo
 * @property string $subtitulo
 * @property string $texto
 * @property date $fecha
 * @property Doctrine_Collection $Autores
 * @property Doctrine_Collection $Secciones
 * @property Doctrine_Collection $AutorNoticia
 * @property Doctrine_Collection $SeccionNoticia
 * @property Doctrine_Collection $Comentario
 * 
 * @method string              getTitulo()         Returns the current record's "titulo" value
 * @method string              getSubtitulo()      Returns the current record's "subtitulo" value
 * @method string              getTexto()          Returns the current record's "texto" value
 * @method date                getFecha()          Returns the current record's "fecha" value
 * @method Doctrine_Collection getAutores()        Returns the current record's "Autores" collection
 * @method Doctrine_Collection getSecciones()      Returns the current record's "Secciones" collection
 * @method Doctrine_Collection getAutorNoticia()   Returns the current record's "AutorNoticia" collection
 * @method Doctrine_Collection getSeccionNoticia() Returns the current record's "SeccionNoticia" collection
 * @method Doctrine_Collection getComentario()     Returns the current record's "Comentario" collection
 * @method Noticia             setTitulo()         Sets the current record's "titulo" value
 * @method Noticia             setSubtitulo()      Sets the current record's "subtitulo" value
 * @method Noticia             setTexto()          Sets the current record's "texto" value
 * @method Noticia             setFecha()          Sets the current record's "fecha" value
 * @method Noticia             setAutores()        Sets the current record's "Autores" collection
 * @method Noticia             setSecciones()      Sets the current record's "Secciones" collection
 * @method Noticia             setAutorNoticia()   Sets the current record's "AutorNoticia" collection
 * @method Noticia             setSeccionNoticia() Sets the current record's "SeccionNoticia" collection
 * @method Noticia             setComentario()     Sets the current record's "Comentario" collection
 * 
 * @package    sf2013
 * @subpackage model
 * @author     Javi
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNoticia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('noticia');
        $this->hasColumn('titulo', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('subtitulo', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
        $this->hasColumn('texto', 'string', 10000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10000,
             ));
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUser as Autores', array(
             'refClass' => 'AutorNoticia',
             'local' => 'noticia_id',
             'foreign' => 'autor_id'));

        $this->hasMany('Seccion as Secciones', array(
             'refClass' => 'SeccionNoticia',
             'local' => 'noticia_id',
             'foreign' => 'seccion_id'));

        $this->hasMany('AutorNoticia', array(
             'local' => 'id',
             'foreign' => 'noticia_id'));

        $this->hasMany('SeccionNoticia', array(
             'local' => 'id',
             'foreign' => 'noticia_id'));

        $this->hasMany('Comentario', array(
             'local' => 'id',
             'foreign' => 'noticia_id'));
    }
}