<?php

/**
 * BaseComentarioUsuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $comentario_id
 * @property integer $usuario_id
 * @property Comentario $Comentario
 * 
 * @method integer           getComentarioId()  Returns the current record's "comentario_id" value
 * @method integer           getUsuarioId()     Returns the current record's "usuario_id" value
 * @method Comentario        getComentario()    Returns the current record's "Comentario" value
 * @method ComentarioUsuario setComentarioId()  Sets the current record's "comentario_id" value
 * @method ComentarioUsuario setUsuarioId()     Sets the current record's "usuario_id" value
 * @method ComentarioUsuario setComentario()    Sets the current record's "Comentario" value
 * 
 * @package    sf2013
 * @subpackage model
 * @author     Javi
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComentarioUsuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comentario_usuario');
        $this->hasColumn('comentario_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('usuario_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Comentario', array(
             'local' => 'comentario_id',
             'foreign' => 'id'));
    }
}