<?php

/**
 * BaseSeccion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $tipo
 * @property string $seccion
 * @property Doctrine_Collection $Noticias
 * @property Doctrine_Collection $SeccionNoticia
 * 
 * @method string              getTipo()           Returns the current record's "tipo" value
 * @method string              getSeccion()        Returns the current record's "seccion" value
 * @method Doctrine_Collection getNoticias()       Returns the current record's "Noticias" collection
 * @method Doctrine_Collection getSeccionNoticia() Returns the current record's "SeccionNoticia" collection
 * @method Seccion             setTipo()           Sets the current record's "tipo" value
 * @method Seccion             setSeccion()        Sets the current record's "seccion" value
 * @method Seccion             setNoticias()       Sets the current record's "Noticias" collection
 * @method Seccion             setSeccionNoticia() Sets the current record's "SeccionNoticia" collection
 * 
 * @package    sf2013
 * @subpackage model
 * @author     Javi
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSeccion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('seccion');
        $this->hasColumn('tipo', 'string', 15, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 15,
             ));
        $this->hasColumn('seccion', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Noticia as Noticias', array(
             'refClass' => 'SeccionNoticia',
             'local' => 'seccion_id',
             'foreign' => 'noticia_id'));

        $this->hasMany('SeccionNoticia', array(
             'local' => 'id',
             'foreign' => 'seccion_id'));
    }
}