<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/04/18 10:30:25
$this->security = array (
  'login' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
