<?php

/**
 * AutorNoticiaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AutorNoticiaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AutorNoticiaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AutorNoticia');
    }
}