<?php

/**
 * ComentarioNoticiaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ComentarioNoticiaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ComentarioNoticiaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ComentarioNoticia');
    }
}