<?php

/**
 * Comentario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf2013
 * @subpackage model
 * @author     Javi
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Comentario extends BaseComentario
{
	public function getUsuario($comentario)
 {
  $usuario=Doctrine_Query::create()->from('sfguarduser u')->select('u.username')->where('u.id = ?', $comentario->getUsuario_id())->fetchOne();
  return $usuario;
 }
 public function getNoticia($comentario)
 {
  $noticia=Doctrine_Query::create()->from('noticia n')->select('n.id')->where('n.id = ?', $comentario->getNoticia_id())->fetchOne();
  return $noticia;
 }
}
