<?php

/**
 * ComentarioUsuarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ComentarioUsuarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ComentarioUsuarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ComentarioUsuario');
    }
}