<?php

/**
 * SeccionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SeccionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SeccionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Seccion');
    }
}