<?php

/**
 * SeccionNoticiaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SeccionNoticiaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SeccionNoticiaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SeccionNoticia');
    }
}