<?php

/**
 * Seccion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf2013
 * @subpackage model
 * @author     Javi
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Seccion extends BaseSeccion
{
	public function getNoticias($seccion)
	{
		$noticias = Doctrine_Query::create() -> from('Noticia n') -> leftJoin('n.SeccionNoticia sn') -> leftJoin('sn.Seccion s') -> where('s.seccion = ?',$seccion -> getSeccion()) -> orderBy('n.fecha DESC') -> execute();
		return $noticias;
	}
}
