<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/04/11 13:09:04

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost; dbname=sf2013_test',
  'username' => 'sf2013',
  'password' => 'sf2013',
  'name' => 'doctrine',
)),);
