<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/04/12 09:31:30

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=sf2013',
  'username' => 'sf2013',
  'password' => 'sf2013',
  'name' => 'doctrine',
)),);
